version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

    volumes:
      - ./tcapy:/tcapy/tcapy:ro
      - ./tests:/tcapy/test:ro
      - ./artifacts:/antarctic/artifacts
      - ./source:/source:ro
    environment:
      - Maffay = 1
    depends_on:
      - influx

  influx:
      image: influxdb:1.8.0


